<a href="https://colab.research.google.com/github/Omniaaaaaaa/transformer/blob/main/transformerr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

def softmax(x):
    x = x - np.max(x, axis=-1, keepdims=True)
    e_x = np.exp(x / 1.5)   # temperature to make attention smoother
    return e_x / e_x.sum(axis=-1, keepdims=True)

def normalize(x):
    return x / (np.linalg.norm(x, axis=-1, keepdims=True) + 1e-8)

def self_attention(Q, K, V):
    d_k = Q.shape[-1]

    # Normalize Q and K to avoid very sharp attention values
    Q = normalize(Q)
    K = normalize(K)

    # Attention scores = QK^T / sqrt(d_k)
    scores = np.dot(Q, K.T) / np.sqrt(d_k)

    # Convert scores into probabilities
    attention_weights = softmax(scores)

    # Final attention output
    output = np.dot(attention_weights, V)

    return scores, attention_weights, output


# Sentence tokens
tokens = ['What', 'are', 'the', 'symptoms', 'of', 'diabetes', '?']

np.random.seed(42)

seq_len = len(tokens)
d_model = 8
d_k = 4
d_v = 4

# Random embeddings and weight matrices
X = np.random.randn(seq_len, d_model) * 0.5
W_Q = np.random.randn(d_model, d_k) * 0.5
W_K = np.random.randn(d_model, d_k) * 0.5
W_V = np.random.randn(d_model, d_v) * 0.5

# Compute Q, K, V
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

# Apply self-attention
scores, weights, output = self_attention(Q, K, V)

print("Tokens:")
print(tokens)

print("\nAttention Scores:")
print(np.round(scores, 3))

print("\nAttention Weight Matrix:")
print(np.round(weights, 3))

print("\nHow much each token attends to 'symptoms':")
for i, token in enumerate(tokens):
    print(f"{token:12s} -> {weights[i, 3]:.3f}")

print("\nOutput Representations:")
print(np.round(output, 3))

Tokens:
['What', 'are', 'the', 'symptoms', 'of', 'diabetes', '?']

Attention Scores:
[[ 0.036  0.203  0.1    0.172  0.43   0.154  0.16 ]
 [ 0.011 -0.389 -0.258 -0.143 -0.297  0.066  0.268]
 [ 0.097 -0.345 -0.015 -0.326 -0.459 -0.271 -0.016]
 [-0.188  0.444 -0.211  0.467  0.264  0.354 -0.297]
 [ 0.161 -0.372 -0.029 -0.215 -0.041 -0.012  0.473]
 [-0.105  0.431 -0.077  0.403  0.378  0.29  -0.18 ]
 [ 0.008  0.358  0.225  0.181  0.422  0.038 -0.083]]

Attention Weight Matrix:
[[0.129 0.145 0.135 0.142 0.168 0.14  0.141]
 [0.153 0.117 0.128 0.138 0.125 0.159 0.181]
 [0.172 0.128 0.159 0.129 0.118 0.134 0.159]
 [0.114 0.174 0.112 0.176 0.154 0.164 0.106]
 [0.157 0.11  0.139 0.122 0.138 0.14  0.194]
 [0.118 0.168 0.12  0.165 0.163 0.153 0.112]
 [0.128 0.161 0.148 0.144 0.169 0.13  0.12 ]]

How much each token attends to 'symptoms':
What         -> 0.142
are          -> 0.138
the          -> 0.129
symptoms     -> 0.176
of           -> 0.122
diabetes     -> 0.165
?            -> 0.144

Output Re