<a href="https://colab.research.google.com/github/Omniaaaaaaa/transformer/blob/main/transformerr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / e_x.sum(axis=-1, keepdims=True)

def self_attention(Q, K, V):
    d_k = Q.shape[-1]
    scores = np.dot(Q, K.T) / np.sqrt(d_k)
    attention_weights = softmax(scores)
    output = np.dot(attention_weights, V)
    return attention_weights, output

# "What are the symptoms of diabetes?"
np.random.seed(42)
tokens  = ['What', 'are', 'the', 'symptoms', 'of', 'diabetes', '?']
seq_len = len(tokens)
d_model, d_k, d_v = 8, 4, 4

X   = np.random.randn(seq_len, d_model)
W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_v)

Q = X @ W_Q
K = X @ W_K
V = X @ W_V

weights, output = self_attention(Q, K, V)

print("Attention Weight Matrix:")
print(np.round(weights, 3))
print("\nOutput Representations:")
print(np.round(output, 3))
print("\nAttention on 'symptoms' from each token:")
for i, t in enumerate(tokens):
    print(f"  {t:12s} -> {weights[i, 3]:.3f}")

Attention Weight Matrix:
[[0.    0.    0.    0.    1.    0.    0.   ]
 [0.001 0.    0.    0.    0.    0.002 0.997]
 [0.916 0.    0.047 0.    0.    0.    0.037]
 [0.    0.639 0.    0.335 0.025 0.001 0.   ]
 [0.    0.    0.    0.    0.    0.    1.   ]
 [0.    0.306 0.    0.04  0.654 0.    0.   ]
 [0.    0.006 0.    0.    0.994 0.    0.   ]]

Output Representations:
[[-0.104 -6.905  5.888 -0.015]
 [ 1.103 -2.414 -0.493 -0.148]
 [-0.287  0.722 -2.801  0.028]
 [-0.509 -1.288  4.072  1.771]
 [ 1.102 -2.42  -0.496 -0.151]
 [-0.352 -5.214  5.516  0.439]
 [-0.109 -6.879  5.884 -0.009]]

Attention on 'symptoms' from each token:
  What         -> 0.000
  are          -> 0.000
  the          -> 0.000
  symptoms     -> 0.335
  of           -> 0.000
  diabetes     -> 0.040
  ?            -> 0.000
